### ISSUE TITLE
error when uploading png

### ISSUE THREAD

**Issue by FraMecca** [gnstaxo/imageboard#9]
```
Serving on http://0.0.0.0:5555
Traceback (most recent call last):
  File "/home/chan/.local/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 610, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chan/.local/lib/python3.7/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/chan/.local/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "./backend.py", line 310, in post_reply
    (config['uploads.strip_metadata'] == 'True'), is_reply=True)
  File "/home/chan/imageboard/utils.py", line 59, in file_validation
    thumbnail(save_path, refnum, ext, is_reply)
  File "/home/chan/imageboard/utils.py", line 37, in thumbnail
    im.save(save_path)
  File "/home/chan/.local/lib/python3.7/site-packages/PIL/Image.py", line 2164, in save
    save_handler(self, fp, filename)
  File "/home/chan/.local/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 612, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode P as JPEG
```

**Comment by gnstaxo** [comment]
Hmm, I don't get any errors, try updating to the latest version of Pillow

**Comment by FraMecca** [comment]
My pillow version is 8.10

**Comment by FraMecca** [comment]
I'll try as soon as I can
